<?php

return array (
  0 => 
  array (
    'basename' => 'TwoArchiveStories',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoArchiveStories',
    'namespace' => 'Modules\\TwoArchiveStories',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoArchiveStories/',
    'slug' => 'two_archive_stories',
    'type' => 'module',
  ),
  1 => 
  array (
    'basename' => 'TwoAuthors',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoAuthors',
    'namespace' => 'Modules\\TwoAuthors',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoAuthors/',
    'slug' => 'two_authors',
    'type' => 'module',
  ),
  2 => 
  array (
    'basename' => 'TwoBackend',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Themes/TwoBackend',
    'namespace' => 'Themes\\TwoBackend',
    'order' => 9001,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/themes/TwoBackend/',
    'slug' => 'two_backend',
    'type' => 'theme',
  ),
  3 => 
  array (
    'basename' => 'TwoBanners',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoBanners',
    'namespace' => 'Modules\\TwoBanners',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoBanners/',
    'slug' => 'two_banners',
    'type' => 'module',
  ),
  4 => 
  array (
    'basename' => 'TwoBlocks',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoBlocks',
    'namespace' => 'Modules\\TwoBlocks',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoBlocks/',
    'slug' => 'two_blocks',
    'type' => 'module',
  ),
  5 => 
  array (
    'basename' => 'TwoBlocnotes',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoBlocnotes',
    'namespace' => 'Modules\\TwoBlocnotes',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoBlocnotes/',
    'slug' => 'two_blocnotes',
    'type' => 'module',
  ),
  6 => 
  array (
    'basename' => 'TwoCarnet',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoCarnet',
    'namespace' => 'Modules\\TwoCarnet',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoCarnet/',
    'slug' => 'two_carnet',
    'type' => 'module',
  ),
  7 => 
  array (
    'basename' => 'TwoChat',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoChat',
    'namespace' => 'Modules\\TwoChat',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoChat/',
    'slug' => 'two_chat',
    'type' => 'module',
  ),
  8 => 
  array (
    'basename' => 'TwoCluterParadise',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoCluterParadise',
    'namespace' => 'Modules\\TwoCluterParadise',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoCluterParadise/',
    'slug' => 'two_cluter_paradise',
    'type' => 'module',
  ),
  9 => 
  array (
    'basename' => 'TwoComments',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoComments',
    'namespace' => 'Modules\\TwoComments',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoComments/',
    'slug' => 'two_comments',
    'type' => 'module',
  ),
  10 => 
  array (
    'basename' => 'TwoContact',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoContact',
    'namespace' => 'Modules\\TwoContact',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoContact/',
    'slug' => 'two_contact',
    'type' => 'module',
  ),
  11 => 
  array (
    'basename' => 'TwoCore',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoCore',
    'namespace' => 'Modules\\TwoCore',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoCore/',
    'slug' => 'two_core',
    'type' => 'module',
  ),
  12 => 
  array (
    'basename' => 'TwoDownload',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoDownload',
    'namespace' => 'Modules\\TwoDownload',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoDownload/',
    'slug' => 'two_download',
    'type' => 'module',
  ),
  13 => 
  array (
    'basename' => 'TwoEdito',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoEdito',
    'namespace' => 'Modules\\TwoEdito',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoEdito/',
    'slug' => 'two_edito',
    'type' => 'module',
  ),
  14 => 
  array (
    'basename' => 'TwoEphemerids',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoEphemerids',
    'namespace' => 'Modules\\TwoEphemerids',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoEphemerids/',
    'slug' => 'two_ephemerids',
    'type' => 'module',
  ),
  15 => 
  array (
    'basename' => 'TwoFaqs',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoFaqs',
    'namespace' => 'Modules\\TwoFaqs',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoFaqs/',
    'slug' => 'two_faqs',
    'type' => 'module',
  ),
  16 => 
  array (
    'basename' => 'TwoFmanager',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoFmanager',
    'namespace' => 'Modules\\TwoFmanager',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoFmanager/',
    'slug' => 'two_fmanager',
    'type' => 'module',
  ),
  17 => 
  array (
    'basename' => 'TwoForum',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoForum',
    'namespace' => 'Modules\\TwoForum',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoForum/',
    'slug' => 'two_forum',
    'type' => 'module',
  ),
  18 => 
  array (
    'basename' => 'TwoFriend',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoFriend',
    'namespace' => 'Modules\\TwoFriend',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoFriend/',
    'slug' => 'two_friend',
    'type' => 'module',
  ),
  19 => 
  array (
    'basename' => 'TwoFrontend',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Themes/TwoFrontend',
    'namespace' => 'Themes\\TwoFrontend',
    'order' => 9001,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/themes/TwoFrontend/',
    'slug' => 'two_frontend',
    'type' => 'theme',
  ),
  20 => 
  array (
    'basename' => 'TwoGeoloc',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoGeoloc',
    'namespace' => 'Modules\\TwoGeoloc',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoGeoloc/',
    'slug' => 'two_geoloc',
    'type' => 'module',
  ),
  21 => 
  array (
    'basename' => 'TwoGroupes',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoGroupes',
    'namespace' => 'Modules\\TwoGroupes',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoGroupes/',
    'slug' => 'two_groupes',
    'type' => 'module',
  ),
  22 => 
  array (
    'basename' => 'TwoHeadlines',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoHeadlines',
    'namespace' => 'Modules\\TwoHeadlines',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoHeadlines/',
    'slug' => 'two_headlines',
    'type' => 'module',
  ),
  23 => 
  array (
    'basename' => 'TwoInstall',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoInstall',
    'namespace' => 'Modules\\TwoInstall',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoInstall/',
    'slug' => 'two_install',
    'type' => 'module',
  ),
  24 => 
  array (
    'basename' => 'TwoIpban',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoIpban',
    'namespace' => 'Modules\\TwoIpban',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoIpban/',
    'slug' => 'two_ipban',
    'type' => 'module',
  ),
  25 => 
  array (
    'basename' => 'TwoLinks',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoLinks',
    'namespace' => 'Modules\\TwoLinks',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoLinks/',
    'slug' => 'two_links',
    'type' => 'module',
  ),
  26 => 
  array (
    'basename' => 'TwoManuels',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoManuels',
    'namespace' => 'Modules\\TwoManuels',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoManuels/',
    'slug' => 'two_manuels',
    'type' => 'module',
  ),
  27 => 
  array (
    'basename' => 'TwoMaps',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoMaps',
    'namespace' => 'Modules\\TwoMaps',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoMaps/',
    'slug' => 'two_maps',
    'type' => 'module',
  ),
  28 => 
  array (
    'basename' => 'TwoMarquePages',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoMarquePages',
    'namespace' => 'Modules\\TwoMarquePages',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoMarquePages/',
    'slug' => 'two_marque_pages',
    'type' => 'module',
  ),
  29 => 
  array (
    'basename' => 'TwoMemberlist',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoMemberlist',
    'namespace' => 'Modules\\TwoMemberlist',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoMemberlist/',
    'slug' => 'two_memberlist',
    'type' => 'module',
  ),
  30 => 
  array (
    'basename' => 'TwoMessenger',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoMessenger',
    'namespace' => 'Modules\\TwoMessenger',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoMessenger/',
    'slug' => 'two_messenger',
    'type' => 'module',
  ),
  31 => 
  array (
    'basename' => 'TwoMinisites',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoMinisites',
    'namespace' => 'Modules\\TwoMinisites',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoMinisites/',
    'slug' => 'two_minisites',
    'type' => 'module',
  ),
  32 => 
  array (
    'basename' => 'TwoModules',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoModules',
    'namespace' => 'Modules\\TwoModules',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoModules/',
    'slug' => 'two_modules',
    'type' => 'module',
  ),
  33 => 
  array (
    'basename' => 'TwoNews',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoNews',
    'namespace' => 'Modules\\TwoNews',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoNews/',
    'slug' => 'two_news',
    'type' => 'module',
  ),
  34 => 
  array (
    'basename' => 'TwoNewsleter',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoNewsleter',
    'namespace' => 'Modules\\TwoNewsleter',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoNewsleter/',
    'slug' => 'two_newsleter',
    'type' => 'module',
  ),
  35 => 
  array (
    'basename' => 'TwoPages',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoPages',
    'namespace' => 'Modules\\TwoPages',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoPages/',
    'slug' => 'two_pages',
    'type' => 'module',
  ),
  36 => 
  array (
    'basename' => 'TwoPollbooth',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoPollbooth',
    'namespace' => 'Modules\\TwoPollbooth',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoPollbooth/',
    'slug' => 'two_pollbooth',
    'type' => 'module',
  ),
  37 => 
  array (
    'basename' => 'TwoPush',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoPush',
    'namespace' => 'Modules\\TwoPush',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoPush/',
    'slug' => 'two_push',
    'type' => 'module',
  ),
  38 => 
  array (
    'basename' => 'TwoReseauxSociaux',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoReseauxSociaux',
    'namespace' => 'Modules\\TwoReseauxSociaux',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoReseauxSociaux/',
    'slug' => 'two_reseaux_sociaux',
    'type' => 'module',
  ),
  39 => 
  array (
    'basename' => 'TwoReviews',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoReviews',
    'namespace' => 'Modules\\TwoReviews',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoReviews/',
    'slug' => 'two_reviews',
    'type' => 'module',
  ),
  40 => 
  array (
    'basename' => 'TwoRssfeed',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoRssfeed',
    'namespace' => 'Modules\\TwoRssfeed',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoRssfeed/',
    'slug' => 'two_rssfeed',
    'type' => 'module',
  ),
  41 => 
  array (
    'basename' => 'TwoSearch',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoSearch',
    'namespace' => 'Modules\\TwoSearch',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoSearch/',
    'slug' => 'two_search',
    'type' => 'module',
  ),
  42 => 
  array (
    'basename' => 'TwoSessionLog',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoSessionLog',
    'namespace' => 'Modules\\TwoSessionLog',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoSessionLog/',
    'slug' => 'two_session_log',
    'type' => 'module',
  ),
  43 => 
  array (
    'basename' => 'TwoSitemap',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoSitemap',
    'namespace' => 'Modules\\TwoSitemap',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoSitemap/',
    'slug' => 'two_sitemap',
    'type' => 'module',
  ),
  44 => 
  array (
    'basename' => 'TwoStat',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoStat',
    'namespace' => 'Modules\\TwoStat',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoStat/',
    'slug' => 'two_stat',
    'type' => 'module',
  ),
  45 => 
  array (
    'basename' => 'TwoThemes',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoThemes',
    'namespace' => 'Modules\\TwoThemes',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoThemes/',
    'slug' => 'two_themes',
    'type' => 'module',
  ),
  46 => 
  array (
    'basename' => 'TwoTops',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoTops',
    'namespace' => 'Modules\\TwoTops',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoTops/',
    'slug' => 'two_tops',
    'type' => 'module',
  ),
  47 => 
  array (
    'basename' => 'TwoTwi',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoTwi',
    'namespace' => 'Modules\\TwoTwi',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoTwi/',
    'slug' => 'two_twi',
    'type' => 'module',
  ),
  48 => 
  array (
    'basename' => 'TwoUpload',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoUpload',
    'namespace' => 'Modules\\TwoUpload',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoUpload/',
    'slug' => 'two_upload',
    'type' => 'module',
  ),
  49 => 
  array (
    'basename' => 'TwoUsers',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoUsers',
    'namespace' => 'Modules\\TwoUsers',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoUsers/',
    'slug' => 'two_users',
    'type' => 'module',
  ),
  50 => 
  array (
    'basename' => 'TwoWspad',
    'enabled' => true,
    'location' => 'local',
    'name' => 'Modules/TwoWspad',
    'namespace' => 'Modules\\TwoWspad',
    'order' => 20,
    'path' => 'E:/New_Serv_Wamp/New_npds_rwo/modules/TwoWspad/',
    'slug' => 'two_wspad',
    'type' => 'module',
  ),
);
